
---
# Java Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: bankapp-service
  annotations:
    kustomize.toolkit.fluxcd.io/suspend: "true"
spec:
  replicas: 2
  suspend: true
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp
        image: sureshc2024/bankapp:V1123345
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Test@123
---
# Bank Application Service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: bankapp-service
  annotations:
    kustomize.toolkit.fluxcd.io/suspend: "true"
spec:
  type: ClusterIP
  suspend: true
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp
